id: I2E44C7AE
legacy_id: P010354
ocr_import_info:
  bdrc_scan_id: W23904
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T02:10:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:02:13.285095+00:00'
last_modified: 2022-09-02 13:04:20.492856
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23904
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23904
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མར་རྔོག་རྒྱུད་སྡེའི་དབང་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.7709263610450157
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I3203:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3203
      total_pages: 793
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3203.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7613426880571897
    legacy_id: v001
  I3204:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3204
      total_pages: 861
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3204.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.780032279848984
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
